(use-modules (guix)
	     (gnu packages python)
	     (guix python-devtools)
	     (gnu package python-platform)
	     (gnu packagepython-distro)
	     (gnu packages mercurial)
	     (gnu packages curl)
	     (gnu packages node)
	     (gnu packages unzip)
	     (gnu packages zip)
	     (gnu gcc-toolchain))
